import fs from 'node:fs';
const patchFile=(path,replacements)=>{let source=fs.readFileSync(path,'utf8');for(const[from,to]of replacements){if(!source.includes(from)){console.warn(`Checklist notes patch did not find expected source in ${path}`);continue;}source=source.split(from).join(to);}fs.writeFileSync(path,source,'utf8');};
patchFile('src/components/SensoryFoodSafety/SensoryFoodSafetyModule.tsx',[
['<td className="p-2 text-[11px] text-slate-400 max-w-[120px] truncate">{item.morningShift.notes||\'-\'}</td>','<td className="p-2 align-top"><textarea defaultValue={item.morningShift.notes||\'\'} onBlur={e=>{const updated={...sanitationLogB1};const items=updated.items.map((row,rowIndex)=>rowIndex===idx?{...row,morningShift:{...row.morningShift,notes:e.target.value}}:row);void updateSanitationLogB1({...updated,items,bakerySection:activeSection});}} placeholder="ملاحظات" className="w-28 min-h-10 resize-y rounded-lg border border-slate-200 p-2 text-xs" /></td>'],
['<td className="p-2 text-[11px] text-slate-400 max-w-[120px] truncate">{item.eveningShift.notes||\'-\'}</td>','<td className="p-2 align-top"><textarea defaultValue={item.eveningShift.notes||\'\'} onBlur={e=>{const updated={...sanitationLogB1};const items=updated.items.map((row,rowIndex)=>rowIndex===idx?{...row,eveningShift:{...row.eveningShift,notes:e.target.value}}:row);void updateSanitationLogB1({...updated,items,bakerySection:activeSection});}} placeholder="ملاحظات" className="w-28 min-h-10 resize-y rounded-lg border border-slate-200 p-2 text-xs" /></td>'],
['<td className="p-2 text-[11px] text-slate-400 border-l max-w-[100px] truncate">{chk.morningShift.notes||\'-\'}</td>','<td className="p-2 align-top border-l"><textarea defaultValue={chk.morningShift.notes||\'\'} onBlur={e=>{const updated={...foodSafetyLog};const checks=updated.checks.map((row,rowIndex)=>rowIndex===idx?{...row,morningShift:{...row.morningShift,notes:e.target.value}}:row);void updateFoodSafetyLog({...updated,checks,bakerySection:activeSection});}} placeholder="ملاحظات" className="w-28 min-h-10 resize-y rounded-lg border border-slate-200 p-2 text-xs" /></td>'],
['<td className="p-2 text-[11px] text-slate-400 max-w-[100px] truncate">{chk.eveningShift.notes||\'-\'}</td>','<td className="p-2 align-top"><textarea defaultValue={chk.eveningShift.notes||\'\'} onBlur={e=>{const updated={...foodSafetyLog};const checks=updated.checks.map((row,rowIndex)=>rowIndex===idx?{...row,eveningShift:{...row.eveningShift,notes:e.target.value}}:row);void updateFoodSafetyLog({...updated,checks,bakerySection:activeSection});}} placeholder="ملاحظات" className="w-28 min-h-10 resize-y rounded-lg border border-slate-200 p-2 text-xs" /></td>']
]);
patchFile('src/services/qualityPersistenceService.ts',[
["async function saveSanitation(log:DailySanitationLog){const payload={...log,items:log.items.length?log.items:DEFAULT_SANITATION_ITEMS.map(item=>({...item,morningShift:{...item.morningShift},eveningShift:{...item.eveningShift}}))};const parent=isUuid(payload.id)?await updateQualityRow<DailySanitationLog>('sanitation',payload.id,payload):await createQualityRow<DailySanitationLog>('sanitation',payload);await replaceSanitationItems(parent.id,payload.items);return {...parent,items:payload.items};}","async function saveSanitation(log:DailySanitationLog){const payload={...log,items:log.items.length?log.items:DEFAULT_SANITATION_ITEMS.map(item=>({...item,morningShift:{...item.morningShift},eveningShift:{...item.eveningShift}}))};let parent:DailySanitationLog;if(isUuid(payload.id)){parent=await updateQualityRow<DailySanitationLog>('sanitation',payload.id,payload);}else{const{data,error}=await supabase.from(QUALITY_TABLES.sanitation).select('*').eq('date',payload.date).eq('bakery_section',payload.bakerySection).order('created_at',{ascending:false}).limit(1);if(error)throw error;if(data&&data[0])parent=await updateQualityRow<DailySanitationLog>('sanitation',String(data[0].id),payload);else parent=await createQualityRow<DailySanitationLog>('sanitation',payload);}await replaceSanitationItems(parent.id,payload.items);return {...parent,items:payload.items};}"],
["async function saveFoodSafety(log:DailyFoodSafetyLog){const payload={...log,checks:log.checks.length?log.checks:DEFAULT_FOOD_SAFETY_CHECKS.map(item=>({...item,morningShift:{...item.morningShift},eveningShift:{...item.eveningShift}}))};const parent=isUuid(payload.id)?await updateQualityRow<DailyFoodSafetyLog>('foodSafety',payload.id,payload):await createQualityRow<DailyFoodSafetyLog>('foodSafety',payload);await replaceFoodSafetyItems(parent.id,payload.checks);return {...parent,checks:payload.checks};}","async function saveFoodSafety(log:DailyFoodSafetyLog){const payload={...log,checks:log.checks.length?log.checks:DEFAULT_FOOD_SAFETY_CHECKS.map(item=>({...item,morningShift:{...item.morningShift},eveningShift:{...item.eveningShift}}))};let parent:DailyFoodSafetyLog;if(isUuid(payload.id)){parent=await updateQualityRow<DailyFoodSafetyLog>('foodSafety',payload.id,payload);}else{const{data,error}=await supabase.from(QUALITY_TABLES.foodSafety).select('*').eq('date',payload.date).eq('bakery_section',payload.bakerySection).order('created_at',{ascending:false}).limit(1);if(error)throw error;if(data&&data[0])parent=await updateQualityRow<DailyFoodSafetyLog>('foodSafety',String(data[0].id),payload);else parent=await createQualityRow<DailyFoodSafetyLog>('foodSafety',payload);}await replaceFoodSafetyItems(parent.id,payload.checks);return {...parent,checks:payload.checks};}"]
]);
console.log('Checklist notes/persistence patch applied.');