import fs from 'node:fs';
import path from 'node:path';

const filePath = path.resolve('src/services/qualityPersistenceService.ts');
let source = fs.readFileSync(filePath, 'utf8');

const oldSanitation = "async function hydrateSanitation(parent:DailySanitationLog){try{const{data,error}=await supabase.from(QUALITY_TABLES.sanitationChecks).select('*').eq('log_id',parent.id).order('id');if(error)throw error;const items=(data??[]).map(row=>({equipmentName:row.equipment_name,equipmentCode:row.equipment_code??'',morningShift:{startShift:row.morning_start,endShift:row.morning_end,notes:row.morning_notes??undefined},eveningShift:{startShift:row.evening_start,endShift:row.evening_end,notes:row.evening_notes??undefined}}));return{...parent,items:items.length?items:DEFAULT_SANITATION_ITEMS.map(item=>({...item,morningShift:{...item.morningShift},eveningShift:{...item.eveningShift}}))}as DailySanitationLog}catch(error){console.warn('Sanitation details read skipped',error);return{...parent,items:DEFAULT_SANITATION_ITEMS.map(item=>({...item,morningShift:{...item.morningShift},eveningShift:{...item.eveningShift}}))}as DailySanitationLog}}";
const newSanitation = "async function hydrateSanitation(parent:DailySanitationLog){const parentItems=Array.isArray(parent.items)?parent.items:[];if(parentItems.length){return{...parent,items:parentItems}as DailySanitationLog}try{const{data,error}=await supabase.from(QUALITY_TABLES.sanitationChecks).select('*').eq('log_id',parent.id).order('id');if(error)throw error;const items=(data??[]).map(row=>({equipmentName:row.equipment_name,equipmentCode:row.equipment_code??'',morningShift:{startShift:row.morning_start,endShift:row.morning_end,notes:row.morning_notes??undefined},eveningShift:{startShift:row.evening_start,endShift:row.evening_end,notes:row.evening_notes??undefined}}));return{...parent,items:items.length?items:DEFAULT_SANITATION_ITEMS.map(item=>({...item,morningShift:{...item.morningShift},eveningShift:{...item.eveningShift}}))}as DailySanitationLog}catch(error){console.warn('Sanitation details read skipped',error);return{...parent,items:DEFAULT_SANITATION_ITEMS.map(item=>({...item,morningShift:{...item.morningShift},eveningShift:{...item.eveningShift}}))}as DailySanitationLog}}";

const oldFoodSafety = "async function hydrateFoodSafety(parent:DailyFoodSafetyLog){try{const{data,error}=await supabase.from(QUALITY_TABLES.foodSafetyChecks).select('*').eq('log_id',parent.id).order('id');if(error)throw error;const checks=(data??[]).map(row=>({id:row.id,category:row.category,criterion:row.criterion,morningShift:{startShift:row.morning_start,midShift:row.morning_mid,notes:row.morning_notes??undefined},eveningShift:{startShift:row.evening_start,midShift:row.evening_mid,notes:row.evening_notes??undefined}}));return{...parent,checks:checks.length?checks:DEFAULT_FOOD_SAFETY_CHECKS.map(item=>({...item,morningShift:{...item.morningShift},eveningShift:{...item.eveningShift}}))}as DailyFoodSafetyLog}catch(error){console.warn('Food safety details read skipped',error);return{...parent,checks:DEFAULT_FOOD_SAFETY_CHECKS.map(item=>({...item,morningShift:{...item.morningShift},eveningShift:{...item.eveningShift}}))}as DailyFoodSafetyLog}}";
const newFoodSafety = "async function hydrateFoodSafety(parent:DailyFoodSafetyLog){const parentChecks=Array.isArray(parent.checks)?parent.checks:[];if(parentChecks.length){return{...parent,checks:parentChecks}as DailyFoodSafetyLog}try{const{data,error}=await supabase.from(QUALITY_TABLES.foodSafetyChecks).select('*').eq('log_id',parent.id).order('id');if(error)throw error;const checks=(data??[]).map(row=>({id:row.id,category:row.category,criterion:row.criterion,morningShift:{startShift:row.morning_start,midShift:row.morning_mid,notes:row.morning_notes??undefined},eveningShift:{startShift:row.evening_start,midShift:row.evening_mid,notes:row.evening_notes??undefined}}));return{...parent,checks:checks.length?checks:DEFAULT_FOOD_SAFETY_CHECKS.map(item=>({...item,morningShift:{...item.morningShift},eveningShift:{...item.eveningShift}}))}as DailyFoodSafetyLog}catch(error){console.warn('Food safety details read skipped',error);return{...parent,checks:DEFAULT_FOOD_SAFETY_CHECKS.map(item=>({...item,morningShift:{...item.morningShift},eveningShift:{...item.eveningShift}}))}as DailyFoodSafetyLog}}";

if (!source.includes(oldSanitation)) throw new Error('Expected sanitation hydrate implementation was not found.');
if (!source.includes(oldFoodSafety)) throw new Error('Expected food safety hydrate implementation was not found.');
source = source.replace(oldSanitation, newSanitation).replace(oldFoodSafety, newFoodSafety);
fs.writeFileSync(filePath, source, 'utf8');
console.log('Persistence source-of-truth patch applied.');
