import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';
import { UserProfile, UserRole, OperatingParametersLog, DefectItemRow, CoreTemperatureRecord, MetalDetectorRecord, ElectricSieveRecord, AdditiveWeightRecord, SensoryEvaluationRecord, NonConformanceRecord, DailySanitationLog, DailyFoodSafetyLog, FinishedProductReleaseForm, ProductWeightSpecRecord } from '../types';
import { INITIAL_USERS } from '../data/initialData';
import { qualityReportsService, QualityReport, InspectionItem, QualityCheckResult } from '../services/qualityReportsService';
import { loadAllQualityForms, qualityFormPersistence } from '../services/qualityPersistenceService';

interface KPISummary { totalSamplesInspected:number; compliantCount:number; nonCompliantCount:number; warningCount:number; compliancePercentage:number; criticalDeviationsCount:number; releaseStatusB1:'approved'|'pending'|'rejected'; releaseStatusB2:'approved'|'pending'|'rejected'; avgSensoryScore:number; avgCoreTemp:number; ccpFailureCount:number; }
interface AppContextType {
  activeSection:1|2; setActiveSection:(sec:1|2)=>void; currentUser:UserProfile; setCurrentUserRole:(role:UserRole)=>void; setCurrentUserProfile:(user:UserProfile)=>void; isDarkMode:boolean; setIsDarkMode:(val:boolean|((prev:boolean)=>boolean))=>void; activeDate:string; setActiveDate:(date:string)=>void;
  qualityReports:QualityReport[]; inspectionItems:InspectionItem[]; loadQualityReports:()=>Promise<void>; createQualityReport:(report:Omit<QualityReport,'id'|'created_by'|'section'>,results?:Omit<QualityCheckResult,'id'|'report_id'>[])=>Promise<QualityReport>; updateQualityReport:(id:string,patch:Partial<Pick<QualityReport,'date'|'shift'|'status'>>)=>Promise<QualityReport>; saveQualityCheckResults:(reportId:string,results:Omit<QualityCheckResult,'id'|'report_id'>[])=>Promise<QualityCheckResult[]>; deleteQualityReport:(id:string)=>Promise<void>;
  operatingParams:OperatingParametersLog[]; addOperatingParam:(param:Omit<OperatingParametersLog,'id'>)=>void; deleteOperatingParam:(id:string)=>void; defectLogs:DefectItemRow[]; addDefectLog:(log:Omit<DefectItemRow,'id'>)=>void; updateDefectLog:(id:string,log:Partial<DefectItemRow>)=>void; deleteDefectLog:(id:string)=>void;
  coreTemperatures:CoreTemperatureRecord[]; addCoreTemperature:(rec:Omit<CoreTemperatureRecord,'id'>)=>void; deleteCoreTemperature:(id:string)=>void; metalDetectorLogs:MetalDetectorRecord[]; addMetalDetectorRecord:(rec:Omit<MetalDetectorRecord,'id'>)=>void; updateMetalDetectorRecord:(id:string,rec:Partial<MetalDetectorRecord>)=>void; deleteMetalDetectorRecord:(id:string)=>void;
  electricSieveLogs:ElectricSieveRecord[]; addElectricSieveRecord:(rec:Omit<ElectricSieveRecord,'id'>)=>void; deleteElectricSieveRecord:(id:string)=>void; additiveWeights:AdditiveWeightRecord[]; addAdditiveWeightRecord:(rec:Omit<AdditiveWeightRecord,'id'>)=>void; deleteAdditiveWeightRecord:(id:string)=>void;
  sensoryEvaluations:SensoryEvaluationRecord[]; addSensoryEvaluation:(rec:Omit<SensoryEvaluationRecord,'id'>)=>void; deleteSensoryEvaluation:(id:string)=>void; nonConformanceLogs:NonConformanceRecord[]; addNonConformanceRecord:(rec:Omit<NonConformanceRecord,'id'>)=>void; updateNonConformanceRecord:(id:string,rec:Partial<NonConformanceRecord>)=>void; deleteNonConformanceRecord:(id:string)=>void;
  sanitationLogB1:DailySanitationLog; updateSanitationLogB1:(log:DailySanitationLog)=>void; foodSafetyLog:DailyFoodSafetyLog; updateFoodSafetyLog:(log:DailyFoodSafetyLog)=>void; releaseFormB1:FinishedProductReleaseForm; updateReleaseFormB1:(form:Partial<FinishedProductReleaseForm>)=>void; releaseFormB2:FinishedProductReleaseForm; updateReleaseFormB2:(form:Partial<FinishedProductReleaseForm>)=>void;
  productWeightSpecs:ProductWeightSpecRecord[]; addProductWeightSpec:(rec:Omit<ProductWeightSpecRecord,'id'>)=>void; deleteProductWeightSpec:(id:string)=>void; kpi:KPISummary; resetAllData:()=>void; exportDataJSON:()=>string; importDataJSON:(jsonStr:string)=>boolean; triggerMockUpdate:()=>void;
}
const AppContext=createContext<AppContextType|undefined>(undefined);

const emptyRelease=(section:1|2, date:string):FinishedProductReleaseForm=>({id:'',date,day:date,bakerySection:section,products:[],mandatoryConditions:{rawMaterialsCompliant:false,ccpOprpReportsCompliant:false,labAnalysisCompliant:false,labelAndPackagingCompliant:false,customerRequirementsCompliant:false},decision:'pending',qaReleaseOfficerName:'',storekeeperName:''});
const safeString=(value:unknown, fallback='')=>typeof value==='string'?value:fallback;

export const AppProvider:React.FC<{children:React.ReactNode}>=({children})=>{
 const [activeSection,setActiveSection]=useState<1|2>(1);
 const [currentUser,setCurrentUser]=useState<UserProfile>(INITIAL_USERS[0]);
 const [isDarkMode,setIsDarkMode]=useState<boolean>(()=>localStorage.getItem('bakery_theme')==='dark');
 const [activeDate,setActiveDate]=useState<string>('2026-08-20');
 const [qualityReports,setQualityReports]=useState<QualityReport[]>([]); const [inspectionItems,setInspectionItems]=useState<InspectionItem[]>([]);
 const [operatingParams,setOperatingParams]=useState<OperatingParametersLog[]>([]); const [defectLogs,setDefectLogs]=useState<DefectItemRow[]>([]); const [coreTemperatures,setCoreTemperatures]=useState<CoreTemperatureRecord[]>([]); const [metalDetectorLogs,setMetalDetectorLogs]=useState<MetalDetectorRecord[]>([]); const [electricSieveLogs,setElectricSieveLogs]=useState<ElectricSieveRecord[]>([]); const [additiveWeights,setAdditiveWeights]=useState<AdditiveWeightRecord[]>([]); const [sensoryEvaluations,setSensoryEvaluations]=useState<SensoryEvaluationRecord[]>([]); const [nonConformanceLogs,setNonConformanceLogs]=useState<NonConformanceRecord[]>([]); const [sanitationLogB1,setSanitationLogB1]=useState<DailySanitationLog>({id:'',date:activeDate,day:activeDate,bakerySection:1,items:[],inspectorSignature:''}); const [foodSafetyLog,setFoodSafetyLog]=useState<DailyFoodSafetyLog>({id:'',date:activeDate,day:activeDate,bakerySection:1,checks:[],inspectorSignature:''}); const [releaseFormB1,setReleaseFormB1]=useState<FinishedProductReleaseForm>(()=>emptyRelease(1,activeDate)); const [releaseFormB2,setReleaseFormB2]=useState<FinishedProductReleaseForm>(()=>emptyRelease(2,activeDate)); const [productWeightSpecs,setProductWeightSpecs]=useState<ProductWeightSpecRecord[]>([]);

 const loadQualityReports=useCallback(async()=>{try{const [reports,items]=await Promise.all([qualityReportsService.list(activeDate),qualityReportsService.getInspectionItems()]);setQualityReports(reports);setInspectionItems(items)}catch(error){console.warn('Supabase quality report load failed',error)}},[activeDate]);
 const loadAllForms=useCallback(async()=>{try{const data=await loadAllQualityForms(activeDate); setOperatingParams(data.operatingParameters as OperatingParametersLog[]); setDefectLogs(data.defects as DefectItemRow[]); setCoreTemperatures(data.coreTemperatures as CoreTemperatureRecord[]); setMetalDetectorLogs(data.metalDetector as MetalDetectorRecord[]); setElectricSieveLogs(data.electricSieve as ElectricSieveRecord[]); setAdditiveWeights(data.additiveWeights as AdditiveWeightRecord[]); setSensoryEvaluations(data.sensoryEvaluations as SensoryEvaluationRecord[]); setNonConformanceLogs(data.ncr as NonConformanceRecord[]); const san=(data.sanitationLogs as DailySanitationLog[]).find(x=>x.bakerySection===1); const food=(data.foodSafetyLogs as DailyFoodSafetyLog[]).find(x=>x.bakerySection===1); const releases=data.releaseForms as FinishedProductReleaseForm[]; setSanitationLogB1(san ?? {id:'',date:activeDate,day:activeDate,bakerySection:1,items:[],inspectorSignature:''}); setFoodSafetyLog(food ?? {id:'',date:activeDate,day:activeDate,bakerySection:1,checks:[],inspectorSignature:''}); setReleaseFormB1(releases.find(x=>x.bakerySection===1) ?? emptyRelease(1,activeDate)); setReleaseFormB2(releases.find(x=>x.bakerySection===2) ?? emptyRelease(2,activeDate)); setProductWeightSpecs(data.productWeights as ProductWeightSpecRecord[])}catch(error){console.warn('Supabase forms load failed',error)}},[activeDate]);
 useEffect(()=>{void loadQualityReports();void loadAllForms()},[loadQualityReports,loadAllForms]);
 useEffect(()=>{if(isDarkMode){document.documentElement.classList.add('dark');localStorage.setItem('bakery_theme','dark')}else{document.documentElement.classList.remove('dark');localStorage.setItem('bakery_theme','light')}},[isDarkMode]);
 const setCurrentUserRole=(role:UserRole)=>setCurrentUser(INITIAL_USERS.find(u=>u.role===role)||INITIAL_USERS[0]); const setCurrentUserProfile=(user:UserProfile)=>setCurrentUser({...user});
 const createQualityReport=async(report:Omit<QualityReport,'id'|'created_by'|'section'>,results:Omit<QualityCheckResult,'id'|'report_id'>[]=[])=>{const created=await qualityReportsService.create(report,results);setQualityReports(prev=>[created,...prev.filter(r=>r.id!==created.id)]);return created}; const updateQualityReport=async(id:string,patch:Partial<Pick<QualityReport,'date'|'shift'|'status'>>)=>{const updated=await qualityReportsService.update(id,patch);setQualityReports(prev=>prev.map(r=>r.id===id?updated:r));return updated}; const saveQualityCheckResults=async(reportId:string,results:Omit<QualityCheckResult,'id'|'report_id'>[])=>qualityReportsService.saveResults(reportId,results); const deleteQualityReport=async(id:string)=>{await qualityReportsService.remove(id);setQualityReports(prev=>prev.filter(r=>r.id!==id))};
 const persistCreate=async(table:Parameters<typeof qualityFormPersistence.create>[0],value:Record<string,unknown>)=>qualityFormPersistence.create(table,value); const persistUpdate=async(table:Parameters<typeof qualityFormPersistence.update>[0],id:string,value:Record<string,unknown>)=>qualityFormPersistence.update(table,id,value); const persistDelete=async(table:Parameters<typeof qualityFormPersistence.remove>[0],id:string)=>qualityFormPersistence.remove(table,id);
 const addOperatingParam=async(p:Omit<OperatingParametersLog,'id'>)=>{try{const created=await persistCreate('operatingParameters',p as Record<string,unknown>);setOperatingParams(prev=>[created as OperatingParametersLog,...prev])}catch(e){console.warn(e)}}; const deleteOperatingParam=async(id:string)=>{setOperatingParams(prev=>prev.filter(x=>x.id!==id));try{await persistDelete('operatingParameters',id)}catch(e){console.warn(e)}};
 const addDefectLog=async(p:Omit<DefectItemRow,'id'>)=>{try{const created=await persistCreate('defects',p as Record<string,unknown>);setDefectLogs(prev=>[created as DefectItemRow,...prev])}catch(e){console.warn(e)}}; const updateDefectLog=async(id:string,p:Partial<DefectItemRow>)=>{try{const updated=await persistUpdate('defects',id,p as Record<string,unknown>);setDefectLogs(prev=>prev.map(x=>x.id===id?updated as DefectItemRow:x))}catch(e){console.warn(e)}}; const deleteDefectLog=async(id:string)=>{setDefectLogs(prev=>prev.filter(x=>x.id!==id));try{await persistDelete('defects',id)}catch(e){console.warn(e)}};
 const addCoreTemperature=async(p:Omit<CoreTemperatureRecord,'id'>)=>{try{const created=await persistCreate('coreTemperatures',p as Record<string,unknown>);setCoreTemperatures(prev=>[created as CoreTemperatureRecord,...prev])}catch(e){console.warn(e)}}; const deleteCoreTemperature=async(id:string)=>{setCoreTemperatures(prev=>prev.filter(x=>x.id!==id));try{await persistDelete('coreTemperatures',id)}catch(e){console.warn(e)}};
 const addMetalDetectorRecord=async(p:Omit<MetalDetectorRecord,'id'>)=>{try{const created=await persistCreate('metalDetector',p as Record<string,unknown>);setMetalDetectorLogs(prev=>[created as MetalDetectorRecord,...prev])}catch(e){console.warn(e)}}; const updateMetalDetectorRecord=async(id:string,p:Partial<MetalDetectorRecord>)=>{try{const updated=await persistUpdate('metalDetector',id,p as Record<string,unknown>);setMetalDetectorLogs(prev=>prev.map(x=>x.id===id?updated as MetalDetectorRecord:x))}catch(e){console.warn(e)}}; const deleteMetalDetectorRecord=async(id:string)=>{setMetalDetectorLogs(prev=>prev.filter(x=>x.id!==id));try{await persistDelete('metalDetector',id)}catch(e){console.warn(e)}};
 const addElectricSieveRecord=async(p:Omit<ElectricSieveRecord,'id'>)=>{try{const created=await persistCreate('electricSieve',p as Record<string,unknown>);setElectricSieveLogs(prev=>[created as ElectricSieveRecord,...prev])}catch(e){console.warn(e)}}; const deleteElectricSieveRecord=async(id:string)=>{setElectricSieveLogs(prev=>prev.filter(x=>x.id!==id));try{await persistDelete('electricSieve',id)}catch(e){console.warn(e)}};
 const addAdditiveWeightRecord=async(p:Omit<AdditiveWeightRecord,'id'>)=>{try{const created=await persistCreate('additiveWeights',p as Record<string,unknown>);setAdditiveWeights(prev=>[created as AdditiveWeightRecord,...prev])}catch(e){console.warn(e)}}; const deleteAdditiveWeightRecord=async(id:string)=>{setAdditiveWeights(prev=>prev.filter(x=>x.id!==id));try{await persistDelete('additiveWeights',id)}catch(e){console.warn(e)}};
 const addSensoryEvaluation=async(p:Omit<SensoryEvaluationRecord,'id'>)=>{try{const created=await persistCreate('sensoryEvaluations',p as Record<string,unknown>);setSensoryEvaluations(prev=>[created as SensoryEvaluationRecord,...prev])}catch(e){console.warn(e)}}; const deleteSensoryEvaluation=async(id:string)=>{setSensoryEvaluations(prev=>prev.filter(x=>x.id!==id));try{await persistDelete('sensoryEvaluations',id)}catch(e){console.warn(e)}};
 const addNonConformanceRecord=async(p:Omit<NonConformanceRecord,'id'>)=>{try{const created=await persistCreate('ncr',p as Record<string,unknown>);setNonConformanceLogs(prev=>[created as NonConformanceRecord,...prev])}catch(e){console.warn(e)}}; const updateNonConformanceRecord=async(id:string,p:Partial<NonConformanceRecord>)=>{try{const updated=await persistUpdate('ncr',id,p as Record<string,unknown>);setNonConformanceLogs(prev=>prev.map(x=>x.id===id?updated as NonConformanceRecord:x))}catch(e){console.warn(e)}}; const deleteNonConformanceRecord=async(id:string)=>{setNonConformanceLogs(prev=>prev.filter(x=>x.id!==id));try{await persistDelete('ncr',id)}catch(e){console.warn(e)}};
 const updateSanitationLogB1=async(log:DailySanitationLog)=>{try{const saved=log.id&&log.id.length>20?await qualityFormPersistence.updateSanitation(log):await qualityFormPersistence.saveSanitation(log);setSanitationLogB1(saved as DailySanitationLog)}catch(e){console.warn(e)}}; const updateFoodSafetyLog=async(log:DailyFoodSafetyLog)=>{try{const saved=log.id&&log.id.length>20?await qualityFormPersistence.updateFoodSafety(log):await qualityFormPersistence.saveFoodSafety(log);setFoodSafetyLog(saved as DailyFoodSafetyLog)}catch(e){console.warn(e)}};
 const updateRelease=(setter:React.Dispatch<React.SetStateAction<FinishedProductReleaseForm>>, current:FinishedProductReleaseForm, patch:Partial<FinishedProductReleaseForm>)=>{const next={...current,...patch};setter(next);void qualityFormPersistence.saveRelease(next).then(saved=>setter(prev=>({...prev,...saved,...next}))).catch(e=>console.warn('Product release save failed',e));};
 const updateReleaseFormB1=async(patch:Partial<FinishedProductReleaseForm>)=>updateRelease(setReleaseFormB1,releaseFormB1,patch); const updateReleaseFormB2=async(patch:Partial<FinishedProductReleaseForm>)=>updateRelease(setReleaseFormB2,releaseFormB2,patch);
 const addProductWeightSpec=async(p:Omit<ProductWeightSpecRecord,'id'>)=>{try{const created=await persistCreate('productWeights',p as Record<string,unknown>);setProductWeightSpecs(prev=>[created as ProductWeightSpecRecord,...prev])}catch(e){console.warn(e)}}; const deleteProductWeightSpec=async(id:string)=>{setProductWeightSpecs(prev=>prev.filter(x=>x.id!==id));try{await persistDelete('productWeights',id)}catch(e){console.warn(e)}};
 const resetAllData=()=>{setOperatingParams([]);setDefectLogs([]);setCoreTemperatures([]);setMetalDetectorLogs([]);setElectricSieveLogs([]);setAdditiveWeights([]);setSensoryEvaluations([]);setNonConformanceLogs([]);setSanitationLogB1({id:'',date:activeDate,day:activeDate,bakerySection:1,items:[],inspectorSignature:''});setFoodSafetyLog({id:'',date:activeDate,day:activeDate,bakerySection:1,checks:[],inspectorSignature:''});setReleaseFormB1(emptyRelease(1,activeDate));setReleaseFormB2(emptyRelease(2,activeDate));setProductWeightSpecs([])};
 const exportDataJSON=()=>JSON.stringify({operatingParams,defectLogs,coreTemperatures,metalDetectorLogs,electricSieveLogs,additiveWeights,sensoryEvaluations,nonConformanceLogs,sanitationLogB1,foodSafetyLog,releaseFormB1,releaseFormB2,productWeightSpecs,exportDate:new Date().toISOString()},null,2); const importDataJSON=()=>false;
 const triggerMockUpdate=()=>{};
 const totalSamplesInspected=defectLogs.reduce((a,c)=>a+c.sampleSize,0)+coreTemperatures.length*5+metalDetectorLogs.length*3+sensoryEvaluations.length*2; const nonCompliantDefects=defectLogs.filter(d=>d.status==='non_compliant').length; const warningDefects=defectLogs.filter(d=>d.status==='warning').length; const compliantDefects=defectLogs.filter(d=>d.status==='compliant').length; const tempFails=coreTemperatures.filter(t=>!t.isCompliant).length; const ccpFails=metalDetectorLogs.filter(m=>!m.isCompliant).length+electricSieveLogs.filter(s=>!s.isCompliant).length; const totalChecks=defectLogs.length+coreTemperatures.length+metalDetectorLogs.length+electricSieveLogs.length; const compliancePercentage=totalChecks?Math.max(0,Math.min(100,Math.round(((totalChecks-(nonCompliantDefects+tempFails+ccpFails))/totalChecks)*100))):0; const criticalDeviationsCount=nonConformanceLogs.length+ccpFails+tempFails; const avgSensoryScore=sensoryEvaluations.length?Number((sensoryEvaluations.reduce((a,c)=>a+c.overallImpressionScore,0)/sensoryEvaluations.length).toFixed(1)):0; const avgCoreTemp=coreTemperatures.length?Number((coreTemperatures.reduce((a,c)=>a+c.coreTemperature,0)/coreTemperatures.length).toFixed(1)):0; const kpi:KPISummary={totalSamplesInspected,compliantCount:compliantDefects,nonCompliantCount:nonCompliantDefects,warningCount:warningDefects,compliancePercentage,criticalDeviationsCount,releaseStatusB1:releaseFormB1.decision,releaseStatusB2:releaseFormB2.decision,avgSensoryScore,avgCoreTemp,ccpFailureCount:ccpFails};
 return <AppContext.Provider value={{activeSection,setActiveSection,currentUser,setCurrentUserRole,setCurrentUserProfile,isDarkMode,setIsDarkMode,activeDate,setActiveDate,qualityReports,inspectionItems,loadQualityReports,createQualityReport,updateQualityReport,saveQualityCheckResults,deleteQualityReport,operatingParams,addOperatingParam,deleteOperatingParam,defectLogs,addDefectLog,updateDefectLog,deleteDefectLog,coreTemperatures,addCoreTemperature,deleteCoreTemperature,metalDetectorLogs,addMetalDetectorRecord,updateMetalDetectorRecord,deleteMetalDetectorRecord,electricSieveLogs,addElectricSieveRecord,deleteElectricSieveRecord,additiveWeights,addAdditiveWeightRecord,deleteAdditiveWeightRecord,sensoryEvaluations,addSensoryEvaluation,deleteSensoryEvaluation,nonConformanceLogs,addNonConformanceRecord,updateNonConformanceRecord,deleteNonConformanceRecord,sanitationLogB1,updateSanitationLogB1,foodSafetyLog,updateFoodSafetyLog,releaseFormB1,updateReleaseFormB1,releaseFormB2,updateReleaseFormB2,productWeightSpecs,addProductWeightSpec,deleteProductWeightSpec,kpi,resetAllData,exportDataJSON,importDataJSON,triggerMockUpdate}}>{children}</AppContext.Provider>;
};
export const useApp=()=>{const c=useContext(AppContext);if(!c)throw new Error('useApp must be used within an AppProvider');return c;};
