import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';
import { UserProfile, UserRole, OperatingParametersLog, DefectItemRow, CoreTemperatureRecord, MetalDetectorRecord, ElectricSieveRecord, AdditiveWeightRecord, SensoryEvaluationRecord, NonConformanceRecord, DailySanitationLog, DailyFoodSafetyLog, FinishedProductReleaseForm, ProductWeightSpecRecord } from '../types';
import { INITIAL_USERS } from '../data/initialData';
import { qualityReportsService, QualityReport, InspectionItem, QualityCheckResult } from '../services/qualityReportsService';
import { loadAllQualityForms, qualityFormPersistence } from '../services/qualityPersistenceService';

interface KPISummary { totalSamplesInspected:number; compliantCount:number; nonCompliantCount:number; warningCount:number; compliancePercentage:number; criticalDeviationsCount:number; releaseStatusB1:'approved'|'pending'|'rejected'; releaseStatusB2:'approved'|'pending'|'rejected'; avgSensoryScore:number; avgCoreTemp:number; ccpFailureCount:number; }
interface AppContextType {
  activeSection:1|2; setActiveSection:(sec:1|2)=>void; currentUser:UserProfile; setCurrentUserRole:(role:UserRole)=>void; setCurrentUserProfile:(user:UserProfile)=>void; isDarkMode:boolean; setIsDarkMode:(val:boolean|((prev:boolean)=>boolean))=>void; activeDate:string; setActiveDate:(date:string)=>void;
  qualityReports:QualityReport[]; inspectionItems:InspectionItem[]; loadQualityReports:()=>Promise<void>; createQualityReport:(report:Omit<QualityReport,'id'|'created_by'|'section'>,results?:Omit<QualityCheckResult,'id'|'report_id'>[])=>Promise<QualityReport>; updateQualityReport:(id:string,patch:Partial<Pick<QualityReport,'date'|'shift'|'status'>>)=>Promise<QualityReport>; saveQualityCheckResults:(reportId:string,results:Omit<QualityCheckResult,'id'|'report_id'>[])=>Promise<QualityCheckResult[]>; deleteQualityReport:(id:string)=>Promise<void>;
  operatingParams:OperatingParametersLog[]; addOperatingParam:(param:Omit<OperatingParametersLog,'id'>)=>void; deleteOperatingParam:(id:string)=>void; defectLogs:DefectItemRow[]; addDefectLog:(log:Omit<DefectItemRow,'id'>)=>void; updateDefectLog:(id:string,log:Partial<DefectItemRow>)=>void; deleteDefectLog:(id:string)=>void;
  coreTemperatures:CoreTemperatureRecord[]; addCoreTemperature:(rec:Omit<CoreTemperatureRecord,'id'>)=>void; deleteCoreTemperature:(id:string)=>void; metalDetectorLogs:MetalDetectorRecord[]; addMetalDetectorRecord:(rec:Omit<MetalDetectorRecord,'id'>)=>void; updateMetalDetectorRecord:(id:string,rec:Partial<MetalDetectorRecord>)=>void; deleteMetalDetectorRecord:(id:string)=>void;
  electricSieveLogs:ElectricSieveRecord[]; addElectricSieveRecord:(rec:Omit<ElectricSieveRecord,'id'>)=>void; deleteElectricSieveRecord:(id:string)=>void; additiveWeights:AdditiveWeightRecord[]; addAdditiveWeightRecord:(rec:Omit<AdditiveWeightRecord,'id'>)=>void; deleteAdditiveWeightRecord:(id:string)=>void;
  sensoryEvaluations:SensoryEvaluationRecord[]; addSensoryEvaluation:(rec:Omit<SensoryEvaluationRecord,'id'>)=>void; deleteSensoryEvaluation:(id:string)=>void; nonConformanceLogs:NonConformanceRecord[]; addNonConformanceRecord:(rec:Omit<NonConformanceRecord,'id'>)=>void; updateNonConformanceRecord:(id:string,rec:Partial<NonConformanceRecord>)=>void; deleteNonConformanceRecord:(id:string)=>void;
  sanitationLogB1:DailySanitationLog; updateSanitationLogB1:(log:DailySanitationLog)=>void; foodSafetyLog:DailyFoodSafetyLog; updateFoodSafetyLog:(log:DailyFoodSafetyLog)=>void; releaseFormB1:FinishedProductReleaseForm; updateReleaseFormB1:(form:Partial<FinishedProductReleaseForm>)=>void; releaseFormB2:FinishedProductReleaseForm; updateReleaseFormB2:(form:Partial<FinishedProductReleaseForm>)=>void;
  productWeightSpecs:ProductWeightSpecRecord[]; addProductWeightSpec:(rec:Omit<ProductWeightSpecRecord,'id'>)=>void; deleteProductWeightSpec:(id:string)=>void; kpi:KPISummary; resetAllData:()=>void; exportDataJSON:()=>string; importDataJSON:(jsonStr:string)=>boolean; triggerMockUpdate:()=>void;
}
const AppContext=createContext<AppContextType|undefined>(undefined); const LOCAL_STORAGE_KEY='bakery_qc_state_v1';
const blankSanitation:DailySanitationLog={id:'',date:'',day:'',bakerySection:1,items:[],inspectorSignature:''};
const blankFoodSafety:DailyFoodSafetyLog={id:'',date:'',day:'',bakerySection:1,checks:[],inspectorSignature:''};
const blankRelease=(section:1|2):FinishedProductReleaseForm=>({id:'',date:'',day:'',bakerySection:section,products:[],mandatoryConditions:{rawMaterialsCompliant:false,ccpOprpReportsCompliant:false,labAnalysisCompliant:false,labelAndPackagingCompliant:false,customerRequirementsCompliant:false},decision:'pending',qaReleaseOfficerName:'',storekeeperName:''});

export const AppProvider:React.FC<{children:React.ReactNode}>=({children})=>{
 const [activeSection,setActiveSection]=useState<1|2>(1); const [currentUser,setCurrentUser]=useState<UserProfile>(INITIAL_USERS[0]); const [isDarkMode,setIsDarkMode]=useState<boolean>(()=>localStorage.getItem('bakery_theme')==='dark'); const [activeDate,setActiveDate]=useState<string>('2026-08-20');
 const [qualityReports,setQualityReports]=useState<QualityReport[]>([]); const [inspectionItems,setInspectionItems]=useState<InspectionItem[]>([]);
 const [operatingParams,setOperatingParams]=useState<OperatingParametersLog[]>([]); const [defectLogs,setDefectLogs]=useState<DefectItemRow[]>([]); const [coreTemperatures,setCoreTemperatures]=useState<CoreTemperatureRecord[]>([]); const [metalDetectorLogs,setMetalDetectorLogs]=useState<MetalDetectorRecord[]>([]); const [electricSieveLogs,setElectricSieveLogs]=useState<ElectricSieveRecord[]>([]); const [additiveWeights,setAdditiveWeights]=useState<AdditiveWeightRecord[]>([]); const [sensoryEvaluations,setSensoryEvaluations]=useState<SensoryEvaluationRecord[]>([]); const [nonConformanceLogs,setNonConformanceLogs]=useState<NonConformanceRecord[]>([]); const [sanitationLogB1,setSanitationLogB1]=useState<DailySanitationLog>(blankSanitation); const [foodSafetyLog,setFoodSafetyLog]=useState<DailyFoodSafetyLog>(blankFoodSafety); const [releaseFormB1,setReleaseFormB1]=useState<FinishedProductReleaseForm>(blankRelease(1)); const [releaseFormB2,setReleaseFormB2]=useState<FinishedProductReleaseForm>(blankRelease(2)); const [productWeightSpecs,setProductWeightSpecs]=useState<ProductWeightSpecRecord[]>([]);
 const loadQualityReports=useCallback(async()=>{try{const [reports,items]=await Promise.all([qualityReportsService.list(activeDate),qualityReportsService.getInspectionItems()]);setQualityReports(reports);setInspectionItems(items)}catch(error){console.warn('Quality report load failed.',error)}},[activeDate]);
 const loadAllForms=useCallback(async()=>{try{const data=await loadAllQualityForms(activeDate); setOperatingParams(data.operatingParameters as OperatingParametersLog[]); setDefectLogs(data.defects as DefectItemRow[]); setCoreTemperatures(data.coreTemperatures as CoreTemperatureRecord[]); setMetalDetectorLogs(data.metalDetector as MetalDetectorRecord[]); setElectricSieveLogs(data.electricSieve as ElectricSieveRecord[]); setAdditiveWeights(data.additiveWeights as AdditiveWeightRecord[]); setSensoryEvaluations(data.sensoryEvaluations as SensoryEvaluationRecord[]); setNonConformanceLogs(data.ncr as NonConformanceRecord[]); const san=(data.sanitationLogs as DailySanitationLog[]).find(x=>x.bakerySection===1); setSanitationLogB1(san??blankSanitation); const food=(data.foodSafetyLogs as DailyFoodSafetyLog[]).find(x=>x.bakerySection===1); setFoodSafetyLog(food??blankFoodSafety); const releases=data.releaseForms as FinishedProductReleaseForm[]; setReleaseFormB1(releases.find(x=>x.bakerySection===1)??blankRelease(1)); setReleaseFormB2(releases.find(x=>x.bakerySection===2)??blankRelease(2)); setProductWeightSpecs(data.productWeights as ProductWeightSpecRecord[])}catch(error){console.warn('Supabase form load failed.',error)}},[activeDate]);
 useEffect(()=>{void loadQualityReports();void loadAllForms()},[loadQualityReports,loadAllForms]);
 useEffect(()=>localStorage.removeItem(`${LOCAL_STORAGE_KEY}_op_params`),[]); useEffect(()=>localStorage.removeItem(`${LOCAL_STORAGE_KEY}_defect_logs`),[]); useEffect(()=>localStorage.removeItem(`${LOCAL_STORAGE_KEY}_core_temp`),[]); useEffect(()=>localStorage.removeItem(`${LOCAL_STORAGE_KEY}_metal_det`),[]); useEffect(()=>localStorage.removeItem(`${LOCAL_STORAGE_KEY}_electric_sieve`),[]); useEffect(()=>localStorage.removeItem(`${LOCAL_STORAGE_KEY}_additives`),[]); useEffect(()=>localStorage.removeItem(`${LOCAL_STORAGE_KEY}_sensory`),[]); useEffect(()=>localStorage.removeItem(`${LOCAL_STORAGE_KEY}_ncr`),[]); useEffect(()=>localStorage.removeItem(`${LOCAL_STORAGE_KEY}_san_b1`),[]); useEffect(()=>localStorage.removeItem(`${LOCAL_STORAGE_KEY}_food_safety`),[]); useEffect(()=>localStorage.removeItem(`${LOCAL_STORAGE_KEY}_rel_b1`),[]); useEffect(()=>localStorage.removeItem(`${LOCAL_STORAGE_KEY}_rel_b2`),[]); useEffect(()=>localStorage.removeItem(`${LOCAL_STORAGE_KEY}_weight_specs`),[]);
 useEffect(()=>{if(isDarkMode){document.documentElement.classList.add('dark');localStorage.setItem('bakery_theme','dark')}else{document.documentElement.classList.remove('dark');localStorage.setItem('bakery_theme','light')}},[isDarkMode]);
 const setCurrentUserRole=(role:UserRole)=>setCurrentUser(INITIAL_USERS.find(u=>u.role===role)||INITIAL_USERS[0]); const setCurrentUserProfile=(user:UserProfile)=>setCurrentUser({...user});
 const createQualityReport=async(report:Omit<QualityReport,'id'|'created_by'|'section'>,results:Omit<QualityCheckResult,'id'|'report_id'>[]=[])=>{const created=await qualityReportsService.create(report,results);setQualityReports(prev=>[created,...prev.filter(r=>r.id!==created.id)]);return created}; const updateQualityReport=async(id:string,patch:Partial<Pick<QualityReport,'date'|'shift'|'status'>>)=>{const updated=await qualityReportsService.update(id,patch);setQualityReports(prev=>prev.map(r=>r.id===id?updated:r));return updated}; const saveQualityCheckResults=async(reportId:string,results:Omit<QualityCheckResult,'id'|'report_id'>[])=>qualityReportsService.saveResults(reportId,results); const deleteQualityReport=async(id:string)=>{await qualityReportsService.remove(id);setQualityReports(prev=>prev.filter(r=>r.id!==id))};
 const addOperatingParam=async(p:Omit<OperatingParametersLog,'id'>)=>{try{const created=await qualityFormPersistence.create('operatingParameters',p as Record<string,unknown>);setOperatingParams(prev=>[created as OperatingParametersLog,...prev])}catch(e){console.warn(e)}}; const deleteOperatingParam=async(id:string)=>{setOperatingParams(prev=>prev.filter(x=>x.id!==id));try{await qualityFormPersistence.remove('operatingParameters',id)}catch(e){console.warn(e)}};
 const addDefectLog=async(l:Omit<DefectItemRow,'id'>)=>{try{const created=await qualityFormPersistence.create('defects',l as Record<string,unknown>);setDefectLogs(prev=>[created as DefectItemRow,...prev])}catch(e){console.warn(e)}}; const updateDefectLog=async(id:string,u:Partial<DefectItemRow>)=>{try{const updated=await qualityFormPersistence.update('defects',id,u as Record<string,unknown>);setDefectLogs(prev=>prev.map(x=>x.id===id?updated as DefectItemRow:x))}catch(e){console.warn(e)}}; const deleteDefectLog=async(id:string)=>{setDefectLogs(prev=>prev.filter(x=>x.id!==id));try{await qualityFormPersistence.remove('defects',id)}catch(e){console.warn(e)}};
 const addCoreTemperature=async(r:Omit<CoreTemperatureRecord,'id'>)=>{try{const created=await qualityFormPersistence.create('coreTemperatures',r as Record<string,unknown>);setCoreTemperatures(prev=>[created as CoreTemperatureRecord,...prev])}catch(e){console.warn(e)}}; const deleteCoreTemperature=async(id:string)=>{setCoreTemperatures(prev=>prev.filter(x=>x.id!==id));try{await qualityFormPersistence.remove('coreTemperatures',id)}catch(e){console.warn(e)}};
 const addMetalDetectorRecord=async(r:Omit<MetalDetectorRecord,'id'>)=>{try{const created=await qualityFormPersistence.create('metalDetector',r as Record<string,unknown>);setMetalDetectorLogs(prev=>[created as MetalDetectorRecord,...prev])}catch(e){console.warn(e)}}; const updateMetalDetectorRecord=async(id:string,u:Partial<MetalDetectorRecord>)=>{try{const updated=await qualityFormPersistence.update('metalDetector',id,u as Record<string,unknown>);setMetalDetectorLogs(prev=>prev.map(x=>x.id===id?updated as MetalDetectorRecord:x))}catch(e){console.warn(e)}}; const deleteMetalDetectorRecord=async(id:string)=>{setMetalDetectorLogs(prev=>prev.filter(x=>x.id!==id));try{await qualityFormPersistence.remove('metalDetector',id)}catch(e){console.warn(e)}};
 const addElectricSieveRecord=async(r:Omit<ElectricSieveRecord,'id'>)=>{try{const created=await qualityFormPersistence.create('electricSieve',r as Record<string,unknown>);setElectricSieveLogs(prev=>[created as ElectricSieveRecord,...prev])}catch(e){console.warn(e)}}; const deleteElectricSieveRecord=async(id:string)=>{setElectricSieveLogs(prev=>prev.filter(x=>x.id!==id));try{await qualityFormPersistence.remove('electricSieve',id)}catch(e){console.warn(e)}};
 const addAdditiveWeightRecord=async(r:Omit<AdditiveWeightRecord,'id'>)=>{try{const created=await qualityFormPersistence.create('additiveWeights',r as Record<string,unknown>);setAdditiveWeights(prev=>[created as AdditiveWeightRecord,...prev])}catch(e){console.warn(e)}}; const deleteAdditiveWeightRecord=async(id:string)=>{setAdditiveWeights(prev=>prev.filter(x=>x.id!==id));try{await qualityFormPersistence.remove('additiveWeights',id)}catch(e){console.warn(e)}};
 const addSensoryEvaluation=async(r:Omit<SensoryEvaluationRecord,'id'>)=>{try{const created=await qualityFormPersistence.create('sensoryEvaluations',r as Record<string,unknown>);setSensoryEvaluations(prev=>[created as SensoryEvaluationRecord,...prev])}catch(e){console.warn(e)}}; const deleteSensoryEvaluation=async(id:string)=>{setSensoryEvaluations(prev=>prev.filter(x=>x.id!==id));try{await qualityFormPersistence.remove('sensoryEvaluations',id)}catch(e){console.warn(e)}};
 const addNonConformanceRecord=async(r:Omit<NonConformanceRecord,'id'>)=>{try{const created=await qualityFormPersistence.create('ncr',r as Record<string,unknown>);setNonConformanceLogs(prev=>[created as NonConformanceRecord,...prev])}catch(e){console.warn(e)}}; const updateNonConformanceRecord=async(id:string,u:Partial<NonConformanceRecord>)=>{try{const updated=await qualityFormPersistence.update('ncr',id,u as Record<string,unknown>);setNonConformanceLogs(prev=>prev.map(x=>x.id===id?updated as NonConformanceRecord:x))}catch(e){console.warn(e)}}; const deleteNonConformanceRecord=async(id:string)=>{setNonConformanceLogs(prev=>prev.filter(x=>x.id!==id));try{await qualityFormPersistence.remove('ncr',id)}catch(e){console.warn(e)}};
 const updateSanitationLogB1=async(log:DailySanitationLog)=>{try{const updated=await qualityFormPersistence.updateSanitation(log);setSanitationLogB1(updated)}catch(e){console.warn(e)}}; const updateFoodSafetyLog=async(log:DailyFoodSafetyLog)=>{try{const updated=await qualityFormPersistence.updateFoodSafety(log);setFoodSafetyLog(updated)}catch(e){console.warn(e)}}; const updateReleaseFormB1=async(form:Partial<FinishedProductReleaseForm>)=>{const next={...releaseFormB1,...form};try{const saved=await qualityFormPersistence.saveRelease(next);setReleaseFormB1(saved)}catch(e){console.warn(e)}}; const updateReleaseFormB2=async(form:Partial<FinishedProductReleaseForm>)=>{const next={...releaseFormB2,...form};try{const saved=await qualityFormPersistence.saveRelease(next);setReleaseFormB2(saved)}catch(e){console.warn(e)}};
 const addProductWeightSpec=async(r:Omit<ProductWeightSpecRecord,'id'>)=>{try{const created=await qualityFormPersistence.create('productWeights',r as Record<string,unknown>);setProductWeightSpecs(prev=>[created as ProductWeightSpecRecord,...prev])}catch(e){console.warn(e)}}; const deleteProductWeightSpec=async(id:string)=>{setProductWeightSpecs(prev=>prev.filter(x=>x.id!==id));try{await qualityFormPersistence.remove('productWeights',id)}catch(e){console.warn(e)}};
 const kpi:KPISummary=(()=>{const samples=coreTemperatures.length; const compliant=coreTemperatures.filter(x=>x.isCompliant).length; const nonCompliant=coreTemperatures.filter(x=>!x.isCompliant).length; const total= samples; return {totalSamplesInspected:samples,compliantCount:compliant,nonCompliantCount:nonCompliant,warningCount:defectLogs.filter(x=>x.status==='warning').length,compliancePercentage:total?Math.round((compliant/total)*100):0,criticalDeviationsCount:defectLogs.filter(x=>x.criticalDeviation).length,releaseStatusB1:releaseFormB1.decision,releaseStatusB2:releaseFormB2.decision,avgSensoryScore:sensoryEvaluations.length?sensoryEvaluations.reduce((a,x)=>a+x.overallImpressionScore,0)/sensoryEvaluations.length:0,avgCoreTemp:coreTemperatures.length?coreTemperatures.reduce((a,x)=>a+x.coreTemperature,0)/coreTemperatures.length:0,ccpFailureCount:metalDetectorLogs.filter(x=>!x.isCompliant).length};})();
 const resetAllData=()=>{setOperatingParams([]);setDefectLogs([]);setCoreTemperatures([]);setMetalDetectorLogs([]);setElectricSieveLogs([]);setAdditiveWeights([]);setSensoryEvaluations([]);setNonConformanceLogs([]);setSanitationLogB1(blankSanitation);setFoodSafetyLog(blankFoodSafety);setReleaseFormB1(blankRelease(1));setReleaseFormB2(blankRelease(2));setProductWeightSpecs([]);setQualityReports([])};
 const exportDataJSON=()=>JSON.stringify({operatingParams,defectLogs,coreTemperatures,metalDetectorLogs,electricSieveLogs,additiveWeights,sensoryEvaluations,nonConformanceLogs,sanitationLogB1,foodSafetyLog,releaseFormB1,releaseFormB2,productWeightSpecs},null,2); const importDataJSON=(_jsonStr:string)=>false; const triggerMockUpdate=()=>{};
 return <AppContext.Provider value={{activeSection,setActiveSection,currentUser,setCurrentUserRole,setCurrentUserProfile,isDarkMode,setIsDarkMode,activeDate,setActiveDate,qualityReports,inspectionItems,loadQualityReports,createQualityReport,updateQualityReport,saveQualityCheckResults,deleteQualityReport,operatingParams,addOperatingParam,deleteOperatingParam,defectLogs,addDefectLog,updateDefectLog,deleteDefectLog,coreTemperatures,addCoreTemperature,deleteCoreTemperature,metalDetectorLogs,addMetalDetectorRecord,updateMetalDetectorRecord,deleteMetalDetectorRecord,electricSieveLogs,addElectricSieveRecord,deleteElectricSieveRecord,additiveWeights,addAdditiveWeightRecord,deleteAdditiveWeightRecord,sensoryEvaluations,addSensoryEvaluation,deleteSensoryEvaluation,nonConformanceLogs,addNonConformanceRecord,updateNonConformanceRecord,deleteNonConformanceRecord,sanitationLogB1,updateSanitationLogB1,foodSafetyLog,updateFoodSafetyLog,releaseFormB1,updateReleaseFormB1,releaseFormB2,updateReleaseFormB2,productWeightSpecs,addProductWeightSpec,deleteProductWeightSpec,kpi,resetAllData,exportDataJSON,importDataJSON,triggerMockUpdate}}>{children}</AppContext.Provider>;
};
export const useApp=()=>{const ctx=useContext(AppContext);if(!ctx)throw new Error('useApp must be used within AppProvider');return ctx};
