import React, { createContext, useContext, useState, useEffect } from 'react';
import { 
  UserProfile, UserRole, OperatingParametersLog, DefectItemRow, CoreTemperatureRecord, MetalDetectorRecord, ElectricSieveRecord, AdditiveWeightRecord, SensoryEvaluationRecord, NonConformanceRecord, DailySanitationLog, DailyFoodSafetyLog, FinishedProductReleaseForm, ProductWeightSpecRecord
} from '../types';
import { INITIAL_USERS, INITIAL_OPERATING_PARAMETERS, INITIAL_DEFECT_LOGS, INITIAL_CORE_TEMPERATURES, INITIAL_METAL_DETECTOR_RECORDS, INITIAL_ELECTRIC_SIEVE_RECORDS, INITIAL_ADDITIVE_RECORDS, INITIAL_SENSORY_EVALUATIONS, INITIAL_NON_CONFORMANCE_RECORDS, INITIAL_SANITATION_LOG_B1, INITIAL_FOOD_SAFETY_LOG, INITIAL_RELEASE_FORM_B1, INITIAL_RELEASE_FORM_B2, INITIAL_PRODUCT_WEIGHT_SPECS } from '../data/initialData';

interface KPISummary { totalSamplesInspected:number; compliantCount:number; nonCompliantCount:number; warningCount:number; compliancePercentage:number; criticalDeviationsCount:number; releaseStatusB1:'approved'|'pending'|'rejected'; releaseStatusB2:'approved'|'pending'|'rejected'; avgSensoryScore:number; avgCoreTemp:number; ccpFailureCount:number; }
interface AppContextType {
  activeSection:1|2; setActiveSection:(sec:1|2)=>void;
  currentUser:UserProfile; setCurrentUserRole:(role:UserRole)=>void; setCurrentUserProfile:(user:UserProfile)=>void;
  isDarkMode:boolean; setIsDarkMode:(val:boolean|((prev:boolean)=>boolean))=>void;
  activeDate:string; setActiveDate:(date:string)=>void;
  operatingParams:OperatingParametersLog[]; addOperatingParam:(param:Omit<OperatingParametersLog,'id'>)=>void; deleteOperatingParam:(id:string)=>void;
  defectLogs:DefectItemRow[]; addDefectLog:(log:Omit<DefectItemRow,'id'>)=>void; updateDefectLog:(id:string,log:Partial<DefectItemRow>)=>void; deleteDefectLog:(id:string)=>void;
  coreTemperatures:CoreTemperatureRecord[]; addCoreTemperature:(rec:Omit<CoreTemperatureRecord,'id'>)=>void; deleteCoreTemperature:(id:string)=>void;
  metalDetectorLogs:MetalDetectorRecord[]; addMetalDetectorRecord:(rec:Omit<MetalDetectorRecord,'id'>)=>void; updateMetalDetectorRecord:(id:string,rec:Partial<MetalDetectorRecord>)=>void; deleteMetalDetectorRecord:(id:string)=>void;
  electricSieveLogs:ElectricSieveRecord[]; addElectricSieveRecord:(rec:Omit<ElectricSieveRecord,'id'>)=>void; deleteElectricSieveRecord:(id:string)=>void;
  additiveWeights:AdditiveWeightRecord[]; addAdditiveWeightRecord:(rec:Omit<AdditiveWeightRecord,'id'>)=>void; deleteAdditiveWeightRecord:(id:string)=>void;
  sensoryEvaluations:SensoryEvaluationRecord[]; addSensoryEvaluation:(rec:Omit<SensoryEvaluationRecord,'id'>)=>void; deleteSensoryEvaluation:(id:string)=>void;
  nonConformanceLogs:NonConformanceRecord[]; addNonConformanceRecord:(rec:Omit<NonConformanceRecord,'id'>)=>void; updateNonConformanceRecord:(id:string,rec:Partial<NonConformanceRecord>)=>void; deleteNonConformanceRecord:(id:string)=>void;
  sanitationLogB1:DailySanitationLog; updateSanitationLogB1:(log:DailySanitationLog)=>void;
  foodSafetyLog:DailyFoodSafetyLog; updateFoodSafetyLog:(log:DailyFoodSafetyLog)=>void;
  releaseFormB1:FinishedProductReleaseForm; updateReleaseFormB1:(form:Partial<FinishedProductReleaseForm>)=>void;
  releaseFormB2:FinishedProductReleaseForm; updateReleaseFormB2:(form:Partial<FinishedProductReleaseForm>)=>void;
  productWeightSpecs:ProductWeightSpecRecord[]; addProductWeightSpec:(rec:Omit<ProductWeightSpecRecord,'id'>)=>void; deleteProductWeightSpec:(id:string)=>void;
  kpi:KPISummary; resetAllData:()=>void; exportDataJSON:()=>string; importDataJSON:(jsonStr:string)=>boolean; triggerMockUpdate:()=>void;
}
const AppContext=createContext<AppContextType|undefined>(undefined);
const LOCAL_STORAGE_KEY='bakery_qc_state_v1';
export const AppProvider:React.FC<{children:React.ReactNode}>=({children})=>{
 const [activeSection,setActiveSection]=useState<1|2>(1);
 const [currentUser,setCurrentUser]=useState<UserProfile>(INITIAL_USERS[0]);
 const [isDarkMode,setIsDarkMode]=useState<boolean>(()=>localStorage.getItem('bakery_theme')==='dark');
 const [activeDate,setActiveDate]=useState<string>('2026-08-20');
 const [operatingParams,setOperatingParams]=useState<OperatingParametersLog[]>(()=>{const s=localStorage.getItem(`${LOCAL_STORAGE_KEY}_op_params`);return s?JSON.parse(s):INITIAL_OPERATING_PARAMETERS});
 const [defectLogs,setDefectLogs]=useState<DefectItemRow[]>(()=>{const s=localStorage.getItem(`${LOCAL_STORAGE_KEY}_defect_logs`);return s?JSON.parse(s):INITIAL_DEFECT_LOGS});
 const [coreTemperatures,setCoreTemperatures]=useState<CoreTemperatureRecord[]>(()=>{const s=localStorage.getItem(`${LOCAL_STORAGE_KEY}_core_temp`);return s?JSON.parse(s):INITIAL_CORE_TEMPERATURES});
 const [metalDetectorLogs,setMetalDetectorLogs]=useState<MetalDetectorRecord[]>(()=>{const s=localStorage.getItem(`${LOCAL_STORAGE_KEY}_metal_det`);return s?JSON.parse(s):INITIAL_METAL_DETECTOR_RECORDS});
 const [electricSieveLogs,setElectricSieveLogs]=useState<ElectricSieveRecord[]>(()=>{const s=localStorage.getItem(`${LOCAL_STORAGE_KEY}_electric_sieve`);return s?JSON.parse(s):INITIAL_ELECTRIC_SIEVE_RECORDS});
 const [additiveWeights,setAdditiveWeights]=useState<AdditiveWeightRecord[]>(()=>{const s=localStorage.getItem(`${LOCAL_STORAGE_KEY}_additives`);return s?JSON.parse(s):INITIAL_ADDITIVE_RECORDS});
 const [sensoryEvaluations,setSensoryEvaluations]=useState<SensoryEvaluationRecord[]>(()=>{const s=localStorage.getItem(`${LOCAL_STORAGE_KEY}_sensory`);return s?JSON.parse(s):INITIAL_SENSORY_EVALUATIONS});
 const [nonConformanceLogs,setNonConformanceLogs]=useState<NonConformanceRecord[]>(()=>{const s=localStorage.getItem(`${LOCAL_STORAGE_KEY}_ncr`);return s?JSON.parse(s):INITIAL_NON_CONFORMANCE_RECORDS});
 const [sanitationLogB1,setSanitationLogB1]=useState<DailySanitationLog>(()=>{const s=localStorage.getItem(`${LOCAL_STORAGE_KEY}_san_b1`);return s?JSON.parse(s):INITIAL_SANITATION_LOG_B1});
 const [foodSafetyLog,setFoodSafetyLog]=useState<DailyFoodSafetyLog>(()=>{const s=localStorage.getItem(`${LOCAL_STORAGE_KEY}_food_safety`);return s?JSON.parse(s):INITIAL_FOOD_SAFETY_LOG});
 const [releaseFormB1,setReleaseFormB1]=useState<FinishedProductReleaseForm>(()=>{const s=localStorage.getItem(`${LOCAL_STORAGE_KEY}_rel_b1`);return s?JSON.parse(s):INITIAL_RELEASE_FORM_B1});
 const [releaseFormB2,setReleaseFormB2]=useState<FinishedProductReleaseForm>(()=>{const s=localStorage.getItem(`${LOCAL_STORAGE_KEY}_rel_b2`);return s?JSON.parse(s):INITIAL_RELEASE_FORM_B2});
 const [productWeightSpecs,setProductWeightSpecs]=useState<ProductWeightSpecRecord[]>(()=>{const s=localStorage.getItem(`${LOCAL_STORAGE_KEY}_weight_specs`);return s?JSON.parse(s):INITIAL_PRODUCT_WEIGHT_SPECS});
 useEffect(()=>localStorage.setItem(`${LOCAL_STORAGE_KEY}_op_params`,JSON.stringify(operatingParams)),[operatingParams]);
 useEffect(()=>localStorage.setItem(`${LOCAL_STORAGE_KEY}_defect_logs`,JSON.stringify(defectLogs)),[defectLogs]);
 useEffect(()=>localStorage.setItem(`${LOCAL_STORAGE_KEY}_core_temp`,JSON.stringify(coreTemperatures)),[coreTemperatures]);
 useEffect(()=>localStorage.setItem(`${LOCAL_STORAGE_KEY}_metal_det`,JSON.stringify(metalDetectorLogs)),[metalDetectorLogs]);
 useEffect(()=>localStorage.setItem(`${LOCAL_STORAGE_KEY}_electric_sieve`,JSON.stringify(electricSieveLogs)),[electricSieveLogs]);
 useEffect(()=>localStorage.setItem(`${LOCAL_STORAGE_KEY}_additives`,JSON.stringify(additiveWeights)),[additiveWeights]);
 useEffect(()=>localStorage.setItem(`${LOCAL_STORAGE_KEY}_sensory`,JSON.stringify(sensoryEvaluations)),[sensoryEvaluations]);
 useEffect(()=>localStorage.setItem(`${LOCAL_STORAGE_KEY}_ncr`,JSON.stringify(nonConformanceLogs)),[nonConformanceLogs]);
 useEffect(()=>localStorage.setItem(`${LOCAL_STORAGE_KEY}_san_b1`,JSON.stringify(sanitationLogB1)),[sanitationLogB1]);
 useEffect(()=>localStorage.setItem(`${LOCAL_STORAGE_KEY}_food_safety`,JSON.stringify(foodSafetyLog)),[foodSafetyLog]);
 useEffect(()=>localStorage.setItem(`${LOCAL_STORAGE_KEY}_rel_b1`,JSON.stringify(releaseFormB1)),[releaseFormB1]);
 useEffect(()=>localStorage.setItem(`${LOCAL_STORAGE_KEY}_rel_b2`,JSON.stringify(releaseFormB2)),[releaseFormB2]);
 useEffect(()=>localStorage.setItem(`${LOCAL_STORAGE_KEY}_weight_specs`,JSON.stringify(productWeightSpecs)),[productWeightSpecs]);
 useEffect(()=>{if(isDarkMode){document.documentElement.classList.add('dark');localStorage.setItem('bakery_theme','dark')}else{document.documentElement.classList.remove('dark');localStorage.setItem('bakery_theme','light')}},[isDarkMode]);
 const setCurrentUserRole=(role:UserRole)=>setCurrentUser(INITIAL_USERS.find(u=>u.role===role)||INITIAL_USERS[0]);
 const setCurrentUserProfile=(user:UserProfile)=>setCurrentUser({...user});
 const addOperatingParam=(p:Omit<OperatingParametersLog,'id'>)=>setOperatingParams(prev=>[{...p,id:`op-${Date.now()}`},...prev]);
 const deleteOperatingParam=(id:string)=>setOperatingParams(prev=>prev.filter(p=>p.id!==id));
 const addDefectLog=(l:Omit<DefectItemRow,'id'>)=>setDefectLogs(prev=>[{...l,id:`def-${Date.now()}`},...prev]);
 const updateDefectLog=(id:string,u:Partial<DefectItemRow>)=>setDefectLogs(prev=>prev.map(i=>i.id===id?{...i,...u}:i));
 const deleteDefectLog=(id:string)=>setDefectLogs(prev=>prev.filter(i=>i.id!==id));
 const addCoreTemperature=(r:Omit<CoreTemperatureRecord,'id'>)=>setCoreTemperatures(prev=>[{...r,id:`ct-${Date.now()}`},...prev]);
 const deleteCoreTemperature=(id:string)=>setCoreTemperatures(prev=>prev.filter(i=>i.id!==id));
 const addMetalDetectorRecord=(r:Omit<MetalDetectorRecord,'id'>)=>setMetalDetectorLogs(prev=>[{...r,id:`md-${Date.now()}`},...prev]);
 const updateMetalDetectorRecord=(id:string,u:Partial<MetalDetectorRecord>)=>setMetalDetectorLogs(prev=>prev.map(i=>i.id===id?{...i,...u}:i));
 const deleteMetalDetectorRecord=(id:string)=>setMetalDetectorLogs(prev=>prev.filter(i=>i.id!==id));
 const addElectricSieveRecord=(r:Omit<ElectricSieveRecord,'id'>)=>setElectricSieveLogs(prev=>[{...r,id:`es-${Date.now()}`},...prev]);
 const deleteElectricSieveRecord=(id:string)=>setElectricSieveLogs(prev=>prev.filter(i=>i.id!==id));
 const addAdditiveWeightRecord=(r:Omit<AdditiveWeightRecord,'id'>)=>setAdditiveWeights(prev=>[{...r,id:`ad-${Date.now()}`},...prev]);
 const deleteAdditiveWeightRecord=(id:string)=>setAdditiveWeights(prev=>prev.filter(i=>i.id!==id));
 const addSensoryEvaluation=(r:Omit<SensoryEvaluationRecord,'id'>)=>setSensoryEvaluations(prev=>[{...r,id:`se-${Date.now()}`},...prev]);
 const deleteSensoryEvaluation=(id:string)=>setSensoryEvaluations(prev=>prev.filter(i=>i.id!==id));
 const addNonConformanceRecord=(r:Omit<NonConformanceRecord,'id'>)=>setNonConformanceLogs(prev=>[{...r,id:`ncr-${Date.now()}`},...prev]);
 const updateNonConformanceRecord=(id:string,u:Partial<NonConformanceRecord>)=>setNonConformanceLogs(prev=>prev.map(i=>i.id===id?{...i,...u}:i));
 const deleteNonConformanceRecord=(id:string)=>setNonConformanceLogs(prev=>prev.filter(i=>i.id!==id));
 const updateSanitationLogB1=(l:DailySanitationLog)=>setSanitationLogB1(l); const updateFoodSafetyLog=(l:DailyFoodSafetyLog)=>setFoodSafetyLog(l);
 const updateReleaseFormB1=(f:Partial<FinishedProductReleaseForm>)=>setReleaseFormB1(p=>({...p,...f})); const updateReleaseFormB2=(f:Partial<FinishedProductReleaseForm>)=>setReleaseFormB2(p=>({...p,...f}));
 const addProductWeightSpec=(r:Omit<ProductWeightSpecRecord,'id'>)=>setProductWeightSpecs(prev=>[{...r,id:`pw-${Date.now()}`},...prev]); const deleteProductWeightSpec=(id:string)=>setProductWeightSpecs(prev=>prev.filter(i=>i.id!==id));
 const resetAllData=()=>{setOperatingParams(INITIAL_OPERATING_PARAMETERS);setDefectLogs(INITIAL_DEFECT_LOGS);setCoreTemperatures(INITIAL_CORE_TEMPERATURES);setMetalDetectorLogs(INITIAL_METAL_DETECTOR_RECORDS);setElectricSieveLogs(INITIAL_ELECTRIC_SIEVE_RECORDS);setAdditiveWeights(INITIAL_ADDITIVE_RECORDS);setSensoryEvaluations(INITIAL_SENSORY_EVALUATIONS);setNonConformanceLogs(INITIAL_NON_CONFORMANCE_RECORDS);setSanitationLogB1(INITIAL_SANITATION_LOG_B1);setFoodSafetyLog(INITIAL_FOOD_SAFETY_LOG);setReleaseFormB1(INITIAL_RELEASE_FORM_B1);setReleaseFormB2(INITIAL_RELEASE_FORM_B2);setProductWeightSpecs(INITIAL_PRODUCT_WEIGHT_SPECS)};
 const exportDataJSON=()=>JSON.stringify({operatingParams,defectLogs,coreTemperatures,metalDetectorLogs,electricSieveLogs,additiveWeights,sensoryEvaluations,nonConformanceLogs,sanitationLogB1,foodSafetyLog,releaseFormB1,releaseFormB2,productWeightSpecs,exportDate:new Date().toISOString()},null,2);
 const importDataJSON=(jsonStr:string)=>{try{const p=JSON.parse(jsonStr);if(p.defectLogs)setDefectLogs(p.defectLogs);if(p.operatingParams)setOperatingParams(p.operatingParams);if(p.coreTemperatures)setCoreTemperatures(p.coreTemperatures);if(p.metalDetectorLogs)setMetalDetectorLogs(p.metalDetectorLogs);if(p.electricSieveLogs)setElectricSieveLogs(p.electricSieveLogs);if(p.additiveWeights)setAdditiveWeights(p.additiveWeights);if(p.sensoryEvaluations)setSensoryEvaluations(p.sensoryEvaluations);if(p.nonConformanceLogs)setNonConformanceLogs(p.nonConformanceLogs);if(p.sanitationLogB1)setSanitationLogB1(p.sanitationLogB1);if(p.foodSafetyLog)setFoodSafetyLog(p.foodSafetyLog);if(p.releaseFormB1)setReleaseFormB1(p.releaseFormB1);if(p.releaseFormB2)setReleaseFormB2(p.releaseFormB2);if(p.productWeightSpecs)setProductWeightSpecs(p.productWeightSpecs);return true}catch{return false}};
 const triggerMockUpdate=()=>{const t=[91.5,93,94.2,95.5,92.8,96][Math.floor(Math.random()*6)];addCoreTemperature({sn:coreTemperatures.length+1,productName:'كرواسون ساده ميجا',time:new Date().toLocaleTimeString('ar-EG',{hour:'2-digit',minute:'2-digit'}),machineCode:'OVEN-01',coreTemperature:t,isCompliant:t>=90,responsiblePerson:currentUser.name,verifiedBy:'م. محمد سيف الإسلام',date:activeDate,bakerySection:activeSection})};
 const totalSamplesInspected=defectLogs.reduce((a,c)=>a+c.sampleSize,0)+coreTemperatures.length*5+metalDetectorLogs.length*3+sensoryEvaluations.length*2;
 const nonCompliantDefects=defectLogs.filter(d=>d.status==='non_compliant').length; const warningDefects=defectLogs.filter(d=>d.status==='warning').length; const compliantDefects=defectLogs.filter(d=>d.status==='compliant').length; const tempFails=coreTemperatures.filter(t=>!t.isCompliant).length; const ccpFails=metalDetectorLogs.filter(m=>!m.isCompliant).length+electricSieveLogs.filter(s=>!s.isCompliant).length; const totalChecks=(defectLogs.length||1)+(coreTemperatures.length||1)+(metalDetectorLogs.length||1); const totalFails=nonCompliantDefects+tempFails+ccpFails; const compliancePercentage=Math.max(0,Math.min(100,Math.round(((totalChecks-totalFails)/totalChecks)*100))); const criticalDeviationsCount=nonConformanceLogs.length+ccpFails+tempFails; const avgSensoryScore=sensoryEvaluations.length?Number((sensoryEvaluations.reduce((a,c)=>a+c.overallImpressionScore,0)/sensoryEvaluations.length).toFixed(1)):9; const avgCoreTemp=coreTemperatures.length?Number((coreTemperatures.reduce((a,c)=>a+c.coreTemperature,0)/coreTemperatures.length).toFixed(1)):93.5;
 const kpi:KPISummary={totalSamplesInspected,compliantCount:compliantDefects,nonCompliantCount:nonCompliantDefects,warningCount:warningDefects,compliancePercentage,criticalDeviationsCount,releaseStatusB1:releaseFormB1.decision,releaseStatusB2:releaseFormB2.decision,avgSensoryScore,avgCoreTemp,ccpFailureCount:ccpFails};
 return <AppContext.Provider value={{activeSection,setActiveSection,currentUser,setCurrentUserRole,setCurrentUserProfile,isDarkMode,setIsDarkMode,activeDate,setActiveDate,operatingParams,addOperatingParam,deleteOperatingParam,defectLogs,addDefectLog,updateDefectLog,deleteDefectLog,coreTemperatures,addCoreTemperature,deleteCoreTemperature,metalDetectorLogs,addMetalDetectorRecord,updateMetalDetectorRecord,deleteMetalDetectorRecord,electricSieveLogs,addElectricSieveRecord,deleteElectricSieveRecord,additiveWeights,addAdditiveWeightRecord,deleteAdditiveWeightRecord,sensoryEvaluations,addSensoryEvaluation,deleteSensoryEvaluation,nonConformanceLogs,addNonConformanceRecord,updateNonConformanceRecord,deleteNonConformanceRecord,sanitationLogB1,updateSanitationLogB1,foodSafetyLog,updateFoodSafetyLog,releaseFormB1,updateReleaseFormB1,releaseFormB2,updateReleaseFormB2,productWeightSpecs,addProductWeightSpec,deleteProductWeightSpec,kpi,resetAllData,exportDataJSON,importDataJSON,triggerMockUpdate}}>{children}</AppContext.Provider>;
};
export const useApp=()=>{const c=useContext(AppContext);if(!c)throw new Error('useApp must be used within an AppProvider');return c;};
